name: Sync Images from Docker Hub to Alibaba Cloud

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨执行同步任务

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: 15398690883
          password: Zhangheng035@..

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com/micolh
          username: malanK
          password: admin@123..

      - name: Pull image from Docker Hub
        run: |
          docker pull arm64v8/mysql:latest

      - name: Tag image for Alibaba Cloud
        run: |
          docker tag arm64v8/mysql:latest registry.cn-hangzhou.aliyuncs.com/micolh/arm64v8/mysql:latest

      - name: Push image to Alibaba Cloud
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/micolh/arm64v8/mysql:latest
